-- Sample data (useful for demo/testing)
-- Password hashes are BCrypt; easiest is to register via API, but these are here for quick DB seeding.
-- NOTE: Replace password_hash with one generated by your backend if you want to log in with these users.

USE smart_focus;

INSERT INTO users (username, password_hash) VALUES
('demo', '$2a$10$wJxZqYx7lB3lX7g9jHqX7u3jM5zHjRr3y7Zxqj3XrQHqvYw0o0z5y')
ON DUPLICATE KEY UPDATE username = username;

-- Find demo user id
SET @demo_id = (SELECT id FROM users WHERE username='demo' LIMIT 1);

INSERT INTO tasks (user_id, title, description, priority, status, estimated_minutes)
VALUES
(@demo_id, 'Build resume project MVP', 'Implement tasks + focus timer + dashboard', 'HIGH', 'IN_PROGRESS', 180),
(@demo_id, 'Read about Angular reactive forms', 'Practice form validation', 'MEDIUM', 'TODO', 45),
(@demo_id, 'Write README steps', 'How to run backend/frontend', 'LOW', 'TODO', 30);

INSERT INTO activity_logs (user_id, type, message)
VALUES
(@demo_id, 'TASK_CREATED', 'Created sample tasks');

